CREATE TABLE driver_session_stats (
    id INTEGER NOT NULL DEFAULT nextval('driver_session_stats_id_seq'::regclass),
    session_id INTEGER,
    steam_id TEXT,
    car_model VARCHAR(255),
    finishing_position INTEGER,
    leader_delta VARCHAR(50),
    fastest_lap DOUBLE PRECISION,
    average_lap DOUBLE PRECISION,
    average_valid_lap DOUBLE PRECISION,
    fastest_possible_lap DOUBLE PRECISION,
    cup_category VARCHAR(50) DEFAULT 'N/A',
    total_race_time DOUBLE PRECISION DEFAULT 0,
    total_off_tracks INTEGER DEFAULT 0,
    fastest_possible_s1 DOUBLE PRECISION,
    fastest_possible_s2 DOUBLE PRECISION,
    fastest_possible_s3 DOUBLE PRECISION,
    car_class VARCHAR(50),
    car_model_id INTEGER,
    car_id INTEGER,
    total_laps INTEGER DEFAULT 0,
    total_valid_laps INTEGER DEFAULT 0,
    drive_time DOUBLE PRECISION DEFAULT 0,
    class_position INTEGER,
    class_delta VARCHAR(50),
    category_position INTEGER,
    category_delta VARCHAR(50),
    race_number INTEGER,
    track_id TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (steam_id) REFERENCES driver_info(steam_id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES session_info(id) ON DELETE CASCADE
);
CREATE INDEX idx_driver_session_stats_car_class ON driver_session_stats (car_class);
