CREATE TABLE driver_track_info (
    id INTEGER NOT NULL DEFAULT nextval('driver_track_info_id_seq'::regclass),
    steam_id TEXT NOT NULL,
    track_id VARCHAR(50) NOT NULL,
    distance_covered DOUBLE PRECISION DEFAULT 0.0,
    total_sessions INTEGER DEFAULT 0,
    best_q_position INTEGER,
    best_r_position INTEGER,
    fastest_q_lap DOUBLE PRECISION,
    fastest_r_lap DOUBLE PRECISION,
    fastest_possible_q DOUBLE PRECISION,
    fastest_possible_r DOUBLE PRECISION,
    fastest_possible_overall DOUBLE PRECISION,
    total_off_tracks INTEGER DEFAULT 0,
    total_laps INTEGER DEFAULT 0,
    average_valid_fp DOUBLE PRECISION,
    average_valid_q DOUBLE PRECISION,
    average_valid_r DOUBLE PRECISION,
    average_fp DOUBLE PRECISION,
    average_q DOUBLE PRECISION,
    average_r DOUBLE PRECISION,
    car_class VARCHAR(50) NOT NULL,
    car_model_id INTEGER NOT NULL,
    best_class_q_position INTEGER,
    best_class_r_position INTEGER,
    best_category_q_position INTEGER,
    best_category_r_position INTEGER,
    r_sessions INTEGER DEFAULT 0,
    q_sessions INTEGER DEFAULT 0,
    fp_sessions INTEGER DEFAULT 0,
    total_valid_laps INTEGER DEFAULT 0,
    PRIMARY KEY (steam_id, track_id, car_model_id),
    FOREIGN KEY (steam_id) REFERENCES driver_info(steam_id) ON DELETE CASCADE,
    FOREIGN KEY (track_id) REFERENCES track_info(track_id) ON DELETE CASCADE
);
