CREATE TABLE team_session_stats (
    id INTEGER NOT NULL DEFAULT nextval('team_session_stats_id_seq'::regclass),
    session_id INTEGER NOT NULL,
    car_id INTEGER NOT NULL,
    car_model_id INTEGER,
    car_class VARCHAR(50),
    cup_category VARCHAR(50) DEFAULT 'N/A',
    finishing_position INTEGER,
    leader_delta VARCHAR(50),
    class_position INTEGER,
    class_delta VARCHAR(50),
    category_position INTEGER,
    category_delta VARCHAR(50),
    total_laps INTEGER DEFAULT 0,
    total_valid_laps INTEGER DEFAULT 0,
    fastest_valid_lap DOUBLE PRECISION,
    fastest_possible_team_time DOUBLE PRECISION,
    avg_lap_time DOUBLE PRECISION,
    avg_valid_lap_time DOUBLE PRECISION,
    drive_time DOUBLE PRECISION DEFAULT 0,
    total_time DOUBLE PRECISION DEFAULT 0,
    drivers_count INTEGER DEFAULT 0,
    race_number INTEGER,
    drivers JSONB,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (session_id, car_id),
    FOREIGN KEY (session_id) REFERENCES session_info(id) ON DELETE CASCADE
);
